### PR TITLE
Final corrections

### PR DESCRIPTION
**Pull request by EdCrux**
Corrections: 

- Aside distance
- Distance between the text and the thumbnail

Cheers

### CODE REVIEW

**Comment by Oluwadamilareolusakin** [comment]
Hey @mariosknl and @EdCrux, your project is prettyl solid, however the HTML validator still throws errors all over the place, please fix and submit for a re-review!

**Comment by EdCrux** [comment]
Hi Olu, We already made it. 

Please check it!

Thanks

**Comment by Anna-Myzukina** [comment]
### Pull Request under the review by Anna Muzykina (TSE)

**Comment by Anna-Myzukina** [comment]
### Hi team!

### Nice job! Project looks! :+1: 
### Project approved!

p.s. Your README.md file is descriptive, but if you want you can use this short [Markdown Cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) to make this file more professional.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*
*Happy coding 😄*

**Comment by Oluwadamilareolusakin** [comment]
Hey @EdCrux and @mariosknl, please don't merge this yet, give me some time to confer with @Anna-Myzukina. In the meantime, here is a link to the error page for your HTML validation [link](https://validator.w3.org/nu/?doc=https%3A%2F%2Fgithub.com%2Fmariosknl%2Futuwebdeb%2Fblob%2FfinalDetails%2Findex.html). Please check it out and see some of the errors I am referring to as being present

**Comment by EdCrux** [comment]
Hi @Oluwadamilareolusakin , we review the validator and there is something wrong with it. Our HTML code has 123 lines, and the validator shows an error on line 295.

Should I make a new pull request, to review it again?

Thanks.

**Comment by Oluwadamilareolusakin** [comment]
@EdCrux hey man! Sorry about that, could you let me know what the error Says?

**Comment by EdCrux** [comment]
Errors appear in the code that doesn´t exist in our page.
[https://validator.w3.org/nu/?doc=https%3A%2F%2Fgithub.com%2Fmariosknl%2Futuwebdeb%2Fblob%2FfinalDetails%2Findex.html](url)

Please guide us on how to solve the problem and submit the project.

**Comment by EdCrux** [comment]
[image: errorValidation.JPG]

**Comment by Oluwadamilareolusakin** [comment]
Here's what I advice, submit for a re-review, I will look in my dashboard and claim it (hopefully it shows up) and once microverse is done for the day, we will find a solution to it. How does that sound?

**Comment by EdCrux** [comment]
We made the new submission for the project. We are waiting for the response.

Thanks for your help!

**Comment by Oluwadamilareolusakin** [comment]
Cheers! :smile:

**Comment by Oluwadamilareolusakin** [comment]
# :rocket:

**Pull request merged**
